### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by kinostl**
Building off of my changes to the scss, I implemented `base16-tomorrow` as a dark mode. Theming can probably easily evolve from here.

I'm not sure how best to document this for new users or make it usable for them. I'm currently making use of this with my own branch that I'm using as an npm module.

### CODE REVIEW

**Comment by kinostl** [comment]
This is what it looks like.
image

**Comment by kinostl** [comment]
Actually, this can probably just extend into a base16 template. That might be a future feature though, and possibly something that would require base16-dark and base16-light themes of their own. Using this in my project i learned stack and cards don't lend to it well and i had to add some custom changes. Not sure how to fold this into here, because they're changes that apply after the plugins are loaded.

Still, [base16-css(https://github.com/fraction/base16-css) uses CSS variables, which means a user can just slap a base16-css file before picnic and be fine.

**Comment by Merovex** [comment]
Could you try a side-by-side? I use the following to dark-mode my site.

Since `html` is inverted, `body > header` (navbar) and `body > footer` are re-inverted. I use `.invert` to tag any other item I want to remain consistent in either light or dark mode. I ended up ripping out all my CSS in favor of this.

```
@media (prefers-color-scheme: dark) {
  html, body > header, body > footer, .invert {
    filter: invert(1) hue-rotate(180deg);
  }
  img:not([src*=".svg"]), .dropimage {
    filter: invert(1) hue-rotate(180deg) saturate(30%);
  }
}
```

**Comment by matthewblott** [comment]
I was working on my own dark mode and didn't realise this was in play, what's the status of this branch?

**Comment by kinostl** [comment]
> I was working on my own dark mode and didn't realise this was in play, what's the status of this branch?
> - @matthewblott 
Absolutely no news on this. I was about to look into trying to add a prefers-color-scheme query to this too and just arbitrarily choose a base16 light and dark for it.

```css
@media (prefers-color-scheme: dark) { @import "base16-dark"; }
@media (prefers-color-scheme: light) { @import "base16-light"; }
@import the-rest-of-picnic
```

**Comment by franciscop** [comment]
Sorry for now I believe this is better implemented on user-land, not as part of the library

**Comment by Jieiku** [comment]
Who has a more or less complete implementation for dark mode? I am going to checkout the branches/forks here for sure, thank you.

**Pull request closed without merging**
